### ISSUE TITLE
phrase-collections - 400 error - Project doesn't belong to phrase collection type

### ISSUE THREAD

**Issue by BernardoSilva** [onesky/api-library-php5#14]
When iI try to 
```sh
POST /projects/58297/phrase-collections
```
I got this error:
```sh
[status] => 400
[message] => Project doesn't belong to phrase collection type
```

the params I am sending are similar to this:
```php
array(1) {
  ["collections"]=>
  array(16) {
    ["campaign_label.en"]=>
    array(2) {
      ["updated"]=>
      array(1) {
        ["string"]=>
        string(7) "Updated"
      }
      ["new"]=>
      array(1) {
        ["string"]=>
        string(3) "New"
      }
    }
}
```

What does it mean?

**Comment by VLMH** [comment]
Phrase collection is a project type in specific data structure.
From the message, it looks like that the project is not in phrase collection type.
The endpoint only serve phrase collection type project. Please update your file and upload it again via `POST projects/:project_id/files`.

p.s. Please send us ticket via support@oneskyapp.com instead of creating issue here in order not to expose sensitive information.
